pipeline {
  agent any
  stages{
    stage('git clone'){
      steps{
       
        git url: 'https://github.com/sonum-mandloi/flask-app-devops.git', branch: 'main'
      }
    }

    stage("permission give"){
      steps{
        sh '''
         usermod -aG docker jenkins
         systemctl restart jenkins
         systemctl restart docker
        '''
      }
    }

    stage('build and push image '){
      steps{
        sh'''
           cd /var/lib/jenkins/workspace/flasks-app-devops
            chmod +x scripts/build.sh

           ./scripts/build.sh
        '''
      }
    }
  }
}

