pipeline {
  agent any
  environment {
        AWS_DEFAULT_REGION = 'ap-southeast-2'
    }
   
  stages{
    stage('git clone'){
      steps{
       
        git url: 'https://github.com/sonum-mandloi/flask-app-devops.git', branch: 'main'
       }
    }

    
    stage('Checkout') {
            steps {
                checkout scm
            }
    }

    stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'SonarScanner'

                    withSonarQubeEnv('SonarQube') {
                        sh """
                        ${scannerHome}/bin/sonar-scanner
                        """
                    }
                }
            }
    }

    stage('Quality Gate') {
       steps {
         echo 'Skipping Quality Gate'
        }
    }

    stage('Build Docker Image') {
          steps {
            sh 'docker build -t sonu7873/flask-app-devops:${BUILD_NUMBER} -f app/DockerFile app'
          }
    }


    stage('Build and Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                        chmod +x scripts/build.sh
                        ./scripts/build.sh
                    '''
                   }
            } 
    }
    stage('Install Ingress Controller') {
    steps {
        sh '''
        chmod +x scripts/ingress.sh
        ./scripts/ingress.sh
        '''
     }
    }

    stage('Deploy to EKS') {
    steps {
        sh '''
        sed -i "s|IMAGE_TAG|${BUILD_NUMBER}|g" k8s/deployment.yaml

        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml

        kubectl rollout status deployment/flask-deployment
        '''
    }
}
  }
}

