pipeline {
  agent any
  stages{
    stage('git clone'){
      steps{
       
        git url: 'https://github.com/sonum-mandloi/flask-app-devops.git', branch: 'main'
      }
    }

      stage('Build and Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                        chmod +x scripts/build.sh
                        ./scripts/build.sh
                    '''
                }
            } 
        }
  }
}

